version: '2'

services:
    db:
        image: mysql
        volumes:
            - "/home/data/mysql/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        volumes:
            - /home/logs/php/:/var/log/
            - ${WWW_APP_PATH}:/var/www
            - /home/deploy/:/var/deploy/
            - ~/.ssh/:~/.ssh/
        container_name: php7.0
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - /home/logs/nginx/:/var/log/nginx
            - ${SITES_AVAILABLE_PATH}:/etc/nginx/sites-available
        environment:
            SITES_AVAILABLE_PATH: ${SITES_AVAILABLE_PATH}
